---

- name: install betterlockscreen
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: 
      - betterlockscreen
      - xss-lock
    state: present
    use: yay

- name: create link for systemd unit
  become: yes
  file:
    path: /usr/local/bin/betterlockscreen
    state: hard
    src: /usr/bin/betterlockscreen

- name: xss-lock
  block:
    - name: enable xss-lock
      lineinfile:
        path: /home/{{ username }}/.config/bspwm/bspwmrc
        line: 'xss-lock -- betterlock -l &'
        insertafter: '^#(OPEN)'
        state: present
    - name: xss-lock kill
      lineinfile:
        path: /home/{{ username }}/.config/bspwm/bspwmrc
        line: 'killall -q xss-lock'
        insertafter: '^#(KILL)'
        state: present

- name: autoreaload wallpaper
  lineinfile:
    path: /home/{{ username }}/.config/bspwm/bspwmrc
    line: 'betterlockscreen -u /home/{{ username }}/wall &'
    insertafter: '^#(OPEN)'
    state: present

- name: install xfce power manager
  become: yes
  pacman:
    name: xfce4-power-manager
    state: present

- name: enable powermanager
  lineinfile:
    path: /home/{{ username }}/.config/bspwm/bspwmrc
    line: 'xfce4-power-manager --daemon &'
    insertafter: '^#(OPEN)'
    state: present
