---

- name: generate japanese local
  become: yes
  locale_gen:
    name: ja_JP.UTF-8
    state: present

- name: add im variables
  blockinfile:
    path: /home/{{ username }}/.xprofile
    block: |
      export GTK_IM_MODULE=fcitx
      export QT_IM_MODULE=fcitx
      export XMODIFIERS=@im=fcitx
    state: present

- name: install packages
  become: yes
  pacman:
    name:
      - fcitx-im
      - fcitx-configtool
      - fcitx-mozc
      - adobe-source-han-sans-jp-fonts
      - adobe-source-han-serif-jp-fonts

- name: enable fcitx
  block:
    - name: open
      lineinfile:
        path: /home/{{ username }}/.config/bspwm/bspwmrc
        line: 'fcitx -d &'
        insertafter: '^#(OPEN)'
        state: present
    - name: kill
      lineinfile:
        path: /home/{{ username }}/.config/bspwm/bspwmrc
        line: 'killall -q fcitx'
        insertafter: '^#(KILL)'
        state: present
