---

- name: install audio packages
  pacman:
    name: "{{ audio_packages }}"
    state: present
  become: yes

- name: audio packages from aur
  kewlfft.aur.aur:
    name: "{{ audio_packages_aur }}"
    use: yay
    state: present
  become: yes
  become_user: aur_builder

- name: ensure pipewire-pulse units are enabled
  systemd:
    scope: user
    name: "{{ item }}"
    enabled: yes
  loop:
    - pipewire-pulse.service
    - pipewire-pulse.socket

