---

- name: install packages
  become: yes
  pacman:
    name: "{{ virt_packages}}"
    state: present

- name: libvirt config
  become: yes
  block:
    - name: libvirt group
      replace:
        regexp: '^#(.*unix_sock_group.*)'
        replace: '\1'
        path: /etc/libvirt/libvirtd.conf
    - name: libvirt socket
      replace:
        path: /etc/libvirt/libvirtd.conf
        regexp: '^#(.*unix_sock_rw_perms.*)'
        replace: '\1'

- name: create libvirt group
  become: yes
  group:
    name: libvirt
    state: present

- name: libvirt group
  become: yes
  user:
    name: "{{ username}}"
    groups:
      - libvirt
      - kvm
    state: present
    append: yes

- name: enable libvirt daemon
  become: yes
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - libvirtd.service
    - virtlogd.service
