---
  
  - name: apps from offical repos
    become: yes
    pacman:
      name: "{{ native_apps }}"
      state: present

  - name: apps from the aur
    become: yes
    become_user: aur_builder
    kewlfft.aur.aur:
      name: "{{ aur_apps }}"
      use: yay
      state: present

  - name: pywal-discord
    lineinfile:
      path: /home/{{ username }}/.config/bspwm/colors.sh
      line: 'pywal-discord update'
      insertafter: '^#(OPEN)'


  - name: enable udiskie
    block:
      - name: bspwmrc
        lineinfile:
          path: /home/{{ username }}/.config/bspwm/bspwmrc
          line: 'udiskie &'
          insertafter: '^#(OPEN)'
          state: present
      - name: bspwmrc skull
        lineinfile:
          path: /home/{{ username }}/.config/bspwm/bspwmrc
          line: 'killall -q udiskie'
          insertafter: '^#(KILL)'
          state: present

  - name: apps from flatpak
    block:
      - name: install flatpak
        become: yes
        pacman:
          name: flatpak
          state: present
      - name: enable flathub
        flatpak_remote:
          name: flathub
          state: present
          method: user
          flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      - name: install flatpak apps
        flatpak:
          name: "{{ flatpak_apps }}"
          method: user
          state: present
          remote: flathub

  - name: radeon-profile
    become: yes
    systemd:
      name: radeon-profile-daemon.service
      enabled: yes
      state: started 
      scope: system
